In [1]:
# numpy stands for numerical python
import numpy as np

In [2]:
X = np.array([1, 2, 3])
print(X)

[1 2 3]


In [4]:
# its type is not list but a numpy n dimensional array
type(X)

numpy.ndarray

In [5]:
l = [4, 5, 10]
X = np.asarray(l)
print(X)

[ 4  5 10]


In [7]:
np.asarray?

Signature: np.asarray(a, dtype=None, order=None)
Docstring:
Convert the input to an array.

Parameters
----------
a : array_like
    Input data, in any form that can be converted to an array.  This
    includes lists, lists of tuples, tuples, tuples of tuples, tuples
    of lists and ndarrays.
dtype : data-type, optional
    By default, the data-type is inferred from the input data.
order : {'C', 'F'}, optional
    Whether to use row-major (C-style) or
    column-major (Fortran-style) memory representation.
    Defaults to 'C'.

Returns
-------
out : ndarray
    Array interpretation of `a`.  No copy is performed if the input
    is already an ndarray with matching dtype and order.  If `a` is a
    subclass of ndarray, a base class ndarray is returned.

See Also
--------
asanyarray : Similar function which passes through subclasses.
ascontiguousarray : Convert input to a contiguous array.
asfarray : Convert input to a floating point ndarray.
asfortranarray : Convert input to an ndarray 

In [18]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Y = np.asarray(lst, str)

In [19]:
print(Y)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [11]:
type(Y)

numpy.ndarray

In [20]:
# prints the shape of the array
# rows and column format
Y.shape

(3, 3)

In [22]:
# for any querise
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
   

In [28]:
# can access the individual item
print(Y[0,0])
print(Y[0,2])

1
3


In [29]:
#can also apply the slicing
Y[0, :]

array(['1', '2', '3'], dtype='<U1')

In [30]:
Y[0:2, :]

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [31]:
zeroMatrix = np.zeros((4, 5))

In [32]:
print(zeroMatrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
# the identity matrix
I = np.eye(4)

In [38]:
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
# making matrix of random size
A = np.random.random((4,5))

In [44]:
print(A)

[[0.54103701 0.9709553  0.05644864 0.92735623 0.70149008]
 [0.36078293 0.21357435 0.68331744 0.26683193 0.90907845]
 [0.86125862 0.311849   0.54732646 0.81836803 0.83099535]
 [0.59114914 0.23675885 0.41745468 0.29056354 0.02176953]]


In [45]:
# can also transpose the matrix
Z = A.T
print(Z)

[[0.54103701 0.36078293 0.86125862 0.59114914]
 [0.9709553  0.21357435 0.311849   0.23675885]
 [0.05644864 0.68331744 0.54732646 0.41745468]
 [0.92735623 0.26683193 0.81836803 0.29056354]
 [0.70149008 0.90907845 0.83099535 0.02176953]]


In [47]:
# reshapping the matrix
A.reshape((10,2))

array([[0.54103701, 0.9709553 ],
       [0.05644864, 0.92735623],
       [0.70149008, 0.36078293],
       [0.21357435, 0.68331744],
       [0.26683193, 0.90907845],
       [0.86125862, 0.311849  ],
       [0.54732646, 0.81836803],
       [0.83099535, 0.59114914],
       [0.23675885, 0.41745468],
       [0.29056354, 0.02176953]])

In [49]:
# some similar function to range
C = np.arange(5)
print(A)

[[0.54103701 0.9709553  0.05644864 0.92735623 0.70149008]
 [0.36078293 0.21357435 0.68331744 0.26683193 0.90907845]
 [0.86125862 0.311849   0.54732646 0.81836803 0.83099535]
 [0.59114914 0.23675885 0.41745468 0.29056354 0.02176953]]


In [50]:
B = np.arange(5)

In [54]:
C = A + B
D = A - B
print(C,"\n\n",D)

[[0.54103701 1.9709553  2.05644864 3.92735623 4.70149008]
 [0.36078293 1.21357435 2.68331744 3.26683193 4.90907845]
 [0.86125862 1.311849   2.54732646 3.81836803 4.83099535]
 [0.59114914 1.23675885 2.41745468 3.29056354 4.02176953]] 

 [[ 0.54103701 -0.0290447  -1.94355136 -2.07264377 -3.29850992]
 [ 0.36078293 -0.78642565 -1.31668256 -2.73316807 -3.09092155]
 [ 0.86125862 -0.688151   -1.45267354 -2.18163197 -3.16900465]
 [ 0.59114914 -0.76324115 -1.58254532 -2.70943646 -3.97823047]]


In [55]:
# linear algebra operation
u = [1, 2, 3]
v = [-1, 0, 1]
#multiplying each point and adding it
p1 = np.inner(u, v)
print(p1)

2


In [57]:
p2 = np.outer(u, v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [58]:
# dot vector
A = np.ones((2,3))
B = np.ones((3, 2))
np.dot(A, B)

array([[3., 3.],
       [3., 3.]])

In [59]:
np.dot(B.T, A.T)

array([[3., 3.],
       [3., 3.]])

In [60]:
# taking only rows or column sums, axis = 0 indicate column sum, axis = 1 indicate the row sum
A.sum(axis = 0)


array([2., 2., 2.])

In [61]:
A.sum(axis = 1)

array([3., 3.])

In [62]:
# finding the maximum value
A.max()

1.0

# practice session